### ISSUE TITLE
不同系统读取文件错误问题

### ISSUE THREAD

**Issue by chang0022** [ITFamary/common-solution-frontend#3]
使用 `path.join()` 代替 字符串拼接
正确：`path.join('file://', files)`
 #错误：`'file://'+ files`

> `path.join`方法用于连接路径。该方法的主要用途在于，会正确使用当前系统的路径分隔符，Unix系统是”/“，Windows系统是”\“。

**Comment by caijiang** [comment]
果然还是太天真了……
已经添加到team中，可以直接push了； 💃
